{{- if .Values.garage.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "akkoma.fullname" . }}-garage-setup
  labels:
    {{- include "akkoma.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "akkoma.fullname" . }}-garage-setup
  labels:
    {{- include "akkoma.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["{{ include "akkoma.fullname" . }}-s3"]
  verbs: ["get", "update", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  resourceNames: ["{{ include "akkoma.fullname" . }}"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "akkoma.fullname" . }}-garage-setup
  labels:
    {{- include "akkoma.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
subjects:
- kind: ServiceAccount
  name: {{ include "akkoma.fullname" . }}-garage-setup
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "akkoma.fullname" . }}-garage-setup
  apiGroup: rbac.authorization.k8s.io
{{- end }}
