{{- if .Values.storage.frontends.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "akkoma.fullname" . }}-frontends
  labels:
    {{- include "akkoma.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.storage.frontends.storageClass }}
  storageClassName: {{ .Values.storage.frontends.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.frontends.size }}
{{- end }}
