{{- if and (eq .Values.storage.type "s3") (not .Values.storage.s3.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akkoma.fullname" . }}-s3
  labels:
    {{- include "akkoma.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key-id: {{ .Values.storage.s3.accessKeyId | quote }}
  secret-access-key: {{ .Values.storage.s3.secretAccessKey | quote }}
{{- end }}
